language: php

php:
  - 5.6

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database laravel;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
